export const areas = [
  {
    slug: "care-access",
    index: "01",
    title: "Designing for Care",
    connection: "Connection with people",
    question: "What changes when design begins with care?",
    description: "Designing with older adults, changing bodies, independence, dignity, family, and community in mind.",
    insight: "Care reveals what ordinary design overlooks. Needs are found by getting close enough to someone's life.",
    projects: ["A Spoon for My Grandfather", "Aging, Body & Independence Studies"],
    color: "#f0b13e",
  },
  {
    slug: "making-systems",
    index: "02",
    title: "Making & Systems",
    connection: "Connection through making",
    question: "How might we make things with fewer processes and more possibilities?",
    description: "Reorganizing structure, manufacturing, assembly, and use so that people can participate in how objects come to life.",
    insight: "When people help complete an object, ownership becomes a relationship rather than a transaction.",
    projects: ["ESTEAST", "Modular Kitchen Organizer", "ALL WE ARE / Modular Shoes", "HOVER", "3D Printed Shoes", "Mat Bag"],
    color: "#dd714d",
  },
  {
    slug: "materials-time",
    index: "03",
    title: "Materials & Time",
    connection: "Connection with consequence",
    question: "What does an object cost beyond its price?",
    description: "Making the hidden timelines of extraction, production, consumption, waste, and degradation possible to experience.",
    insight: "What takes minutes to produce may remain with the planet for centuries.",
    projects: ["Unmaking Time", "Make Less, Create More", "Zero-waste Material Experiments"],
    color: "#d88933",
  },
  {
    slug: "mind-body-behavior",
    index: "04",
    title: "Mind, Body & Behavior",
    connection: "Connection with ourselves",
    question: "How might we design with the body and mind, rather than against them?",
    description: "Exploring anatomy, human performance, meditation, brain waves, attention, habits, and the felt experience of everyday life.",
    insight: "Before improving performance, we must understand what it means to be present in the body.",
    projects: ["Morning OS", "Meditation & Brain Waves", "Human Performance Studies", "Know Yourself"],
    color: "#78aa50",
  },
  {
    slug: "play-ai-interaction",
    index: "05",
    title: "Play, AI & Interaction",
    connection: "Connection through interaction",
    question: "Can technology invite agency instead of demanding attention?",
    description: "Using play, artificial intelligence, and participatory experiences to create curiosity, reflection, and shared language.",
    insight: "Technology should not only capture our attention; it can help us return it to ourselves.",
    projects: ["Design for Play", "AI Companion", "BBgo", "Participatory Experiments"],
    color: "#267ec5",
  },
] as const;

export type Area = (typeof areas)[number];
